name: "Feature request"
description: "Suggest a new idea or enhancement"
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature description
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
