name: Docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 1.8.3
      - name: Install dependencies
        run: |
          poetry install
      - name: Deploy
        run: |
          poetry run mkdocs gh-deploy --force
